name: Build Android APK

on:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: "8.4"

      - name: Build APK
        run: gradle assembleDebug --stacktrace

      - name: Rename APK
        run: |
          cp app/build/outputs/apk/debug/app-debug.apk NathMobileApp.apk

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: NathMobileApp-APK
          path: NathMobileApp.apk

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Nath Mobile Repairing - Latest APK
          body: Latest Nath Mobile Repairing Android APK
          prerelease: false
          files: NathMobileApp.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
